version: 1.0

env: development
server:
  host: 0.0.0.0
  http-port: 8080
log:
  path: "app.log"
  level: -1 
databases:
  postgres:
    host: 127.0.0.1
    password: postgres
    db: mergemoney
    sslmode: disable
    port: 5432
    user: postgres
    connect_timeout: 5
auth:
  key : secret
  key2fa: secret2fa
  key1fa_token_timeout: 300
  key1fa_refresh_timeout: 86400
  key2fa_token_timeout: 300
  key2fa_refresh_timeout: 604800